version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "domain: ci"
      - "no-changelog"
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions:
        patterns:
          - "*"
