//! Configuration for the Zerobus sink.

use vector_lib::configurable::configurable_component;
use vector_lib::sensitive_string::SensitiveString;

use crate::config::{AcknowledgementsConfig, GenerateConfig, Input, SinkConfig, SinkContext};
use crate::sinks::{
    prelude::*,
    util::{BatchConfig, RealtimeSizeBasedDefaultBatchSettings},
};

use vector_lib::codecs::encoding::{ArrowStreamSerializerConfig, BatchSerializerConfig};

use super::{error::ZerobusSinkError, service::ZerobusService, sink::ZerobusSink};

/// Authentication configuration for Databricks.
#[configurable_component]
#[derive(Clone, Debug)]
#[serde(tag = "strategy", rename_all = "snake_case")]
pub enum DatabricksAuthentication {
    /// Authenticate using OAuth 2.0 client credentials.
    #[serde(rename = "oauth")]
    OAuth {
        /// OAuth 2.0 client ID.
        #[configurable(metadata(docs::examples = "${DATABRICKS_CLIENT_ID}"))]
        #[configurable(metadata(docs::examples = "abc123..."))]
        client_id: SensitiveString,

        /// OAuth 2.0 client secret.
        #[configurable(metadata(docs::examples = "${DATABRICKS_CLIENT_SECRET}"))]
        #[configurable(metadata(docs::examples = "secret123..."))]
        client_secret: SensitiveString,
    },

    /// Authenticate via Login service using mTLS bootstrap.
    ///
    /// Used by logging-agent to obtain internal OAuth tokens by authenticating
    /// as a System Service Principal via s2s-proxy.
    #[serde(rename = "login_service")]
    LoginService(crate::databricks_auth::LoginServiceAuthConfig),
}

/// Schema source configuration for defining table schema.
///
/// The schema can be provided as either:
/// - A path to a protobuf descriptor file (.desc or .pb)
/// - Dynamically fetched from the Unity Catalog table
#[configurable_component]
#[derive(Clone, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SchemaSource {
    /// Path to a protobuf descriptor file.
    ///
    /// The file should contain a serialized FileDescriptorSet or DescriptorProto.
    /// These files are typically generated by protoc with the --descriptor_set_out flag.
    ///
    /// Example:
    /// ```sh
    /// protoc --descriptor_set_out=schema.desc --include_imports your_schema.proto
    /// ```
    Path {
        /// Path to the descriptor file.
        #[configurable(metadata(docs::examples = "/path/to/schema.desc"))]
        #[configurable(metadata(docs::examples = "./schema.pb"))]
        path: String,

        /// The message type to use from the descriptor file.
        #[configurable(metadata(docs::examples = "package.Message"))]
        message_type: String,
    },

    /// Dynamically fetch schema from Unity Catalog table.
    ///
    /// This will query the Unity Catalog API to get the table schema and
    /// automatically generate a protobuf descriptor from it.
    /// Uses the same authentication credentials as the sink.
    #[serde(rename = "unity_catalog")]
    UnityCatalog,
}

impl Default for SchemaSource {
    fn default() -> Self {
        SchemaSource::UnityCatalog
    }
}

/// Arrow IPC compression codec for Zerobus Arrow Flight payloads.
#[configurable_component]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Compression {
    /// No compression.
    #[default]
    None,
    /// LZ4 frame compression.
    Lz4Frame,
    /// Zstandard compression.
    Zstd,
}

impl From<Compression> for Option<arrow::ipc::CompressionType> {
    fn from(value: Compression) -> Self {
        match value {
            Compression::None => None,
            Compression::Lz4Frame => Some(arrow::ipc::CompressionType::LZ4_FRAME),
            Compression::Zstd => Some(arrow::ipc::CompressionType::ZSTD),
        }
    }
}

/// Zerobus stream configuration options.
///
/// This is a thin wrapper around the SDK's `ArrowStreamConfigurationOptions` with
/// Vector-specific configuration attributes and custom defaults suitable for Vector's use case.
#[configurable_component]
#[derive(Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ZerobusStreamOptions {
    /// Timeout in milliseconds for flush operations.
    #[serde(default = "default_flush_timeout_ms")]
    #[configurable(metadata(docs::examples = 30000))]
    pub flush_timeout_ms: u64,

    /// Timeout in milliseconds for server acknowledgments.
    #[serde(default = "default_server_ack_timeout_ms")]
    #[configurable(metadata(docs::examples = 60000))]
    pub server_lack_of_ack_timeout_ms: u64,

    /// Arrow IPC compression for Flight payloads. Defaults to no compression.
    #[configurable(derived)]
    #[serde(default, skip_serializing_if = "crate::serde::is_default")]
    pub compression: Compression,
}

impl Default for ZerobusStreamOptions {
    fn default() -> Self {
        Self {
            flush_timeout_ms: default_flush_timeout_ms(),
            server_lack_of_ack_timeout_ms: default_server_ack_timeout_ms(),
            compression: Compression::None,
        }
    }
}

/// Configuration for the Databricks Zerobus sink.
#[configurable_component(sink(
    "databricks_zerobus",
    "Stream observability data to Databricks Unity Catalog via Zerobus."
))]
#[derive(Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ZerobusSinkConfig {
    /// The Zerobus ingestion endpoint URL.
    ///
    /// This should be the full URL to the Zerobus ingestion service.
    #[configurable(metadata(docs::examples = "https://ingest.dev.databricks.com"))]
    #[configurable(metadata(docs::examples = "https://ingest.prod.databricks.com"))]
    pub ingestion_endpoint: String,

    /// The Unity Catalog table name to write to.
    ///
    /// This should be in the format `catalog.schema.table`.
    #[configurable(metadata(docs::examples = "logging_platform.my_team.logs"))]
    #[configurable(metadata(docs::examples = "main.default.vector_logs"))]
    pub table_name: String,

    /// The Unity Catalog endpoint URL.
    ///
    /// This is used for authentication and table metadata.
    #[configurable(metadata(
        docs::examples = "https://dbc-e2f0eb31-2b0e.staging.cloud.databricks.com"
    ))]
    #[configurable(metadata(docs::examples = "https://your-workspace.cloud.databricks.com"))]
    pub unity_catalog_endpoint: String,

    /// Databricks authentication configuration.
    #[configurable(derived)]
    pub auth: DatabricksAuthentication,

    /// Custom identifier appended to the `user-agent` header sent to Databricks.
    ///
    /// The header always includes `Vector/<version>`; when set, this value is
    /// appended after it (e.g. `my-service/1.2`).
    #[serde(default)]
    #[configurable(metadata(docs::examples = "my-service/1.2"))]
    pub user_agent: Option<String>,

    /// Schema definition for the table.
    ///
    /// Defaults to fetching the schema dynamically from Unity Catalog.
    /// Can be omitted from the configuration entirely to use the default.
    #[configurable(derived)]
    #[serde(default)]
    pub schema: SchemaSource,

    /// Zerobus stream configuration options.
    #[serde(default)]
    pub stream_options: ZerobusStreamOptions,

    /// The batch encoding configuration for encoding events in batches.
    ///
    /// Defaults to protobuf batch encoding, which serializes each event
    /// individually as a protobuf message.
    #[configurable(derived)]
    #[serde(default = "default_batch_encoding")]
    pub batch_encoding: BatchSerializerConfig,

    #[configurable(derived)]
    #[serde(default)]
    pub batch: BatchConfig<RealtimeSizeBasedDefaultBatchSettings>,

    #[configurable(derived)]
    #[serde(default)]
    pub request: TowerRequestConfig,

    #[configurable(derived)]
    #[serde(
        default,
        deserialize_with = "crate::serde::bool_or_struct",
        skip_serializing_if = "crate::serde::is_default"
    )]
    pub acknowledgements: AcknowledgementsConfig,
}

impl GenerateConfig for ZerobusSinkConfig {
    fn generate_config() -> toml::Value {
        toml::Value::try_from(Self {
            ingestion_endpoint: "https://ingest.dev.databricks.com".to_string(),
            table_name: "catalog.schema.table".to_string(),
            unity_catalog_endpoint: "https://your-workspace.cloud.databricks.com".to_string(),
            auth: DatabricksAuthentication::OAuth {
                client_id: SensitiveString::from("${DATABRICKS_CLIENT_ID}".to_string()),
                client_secret: SensitiveString::from("${DATABRICKS_CLIENT_SECRET}".to_string()),
            },
            user_agent: None,
            schema: SchemaSource::UnityCatalog,
            stream_options: ZerobusStreamOptions::default(),
            batch_encoding: default_batch_encoding(),
            batch: BatchConfig::default(),
            request: TowerRequestConfig::default(),
            acknowledgements: AcknowledgementsConfig::default(),
        })
        .unwrap()
    }
}

#[async_trait::async_trait]
#[typetag::serde(name = "databricks_zerobus")]
impl SinkConfig for ZerobusSinkConfig {
    async fn build(&self, cx: SinkContext) -> crate::Result<(VectorSink, Healthcheck)> {
        self.validate()?;

        let service = ZerobusService::new(self.clone(), cx.proxy()).await?;
        let healthcheck_service = service.clone();

        let request_limits = self.request.into_settings();

        let sink = ZerobusSink::new(service, request_limits, self.batch.clone())?;

        let healthcheck = async move {
            healthcheck_service
                .ensure_stream()
                .await
                .map_err(|e| e.into())
        };

        Ok((
            VectorSink::from_event_streamsink(sink),
            Box::pin(healthcheck),
        ))
    }

    fn input(&self) -> Input {
        Input::log()
    }

    fn acknowledgements(&self) -> &AcknowledgementsConfig {
        &self.acknowledgements
    }
}

impl ZerobusSinkConfig {
    pub fn validate(&self) -> Result<(), ZerobusSinkError> {
        if self.ingestion_endpoint.is_empty() {
            return Err(ZerobusSinkError::ConfigError {
                message: "ingestion_endpoint cannot be empty".to_string(),
            });
        }

        if self.table_name.is_empty() {
            return Err(ZerobusSinkError::ConfigError {
                message: "table_name cannot be empty".to_string(),
            });
        }

        if !self.table_name.contains('.') {
            return Err(ZerobusSinkError::ConfigError {
                message: "table_name must be in format 'catalog.schema.table'".to_string(),
            });
        }

        if self.unity_catalog_endpoint.is_empty() {
            return Err(ZerobusSinkError::ConfigError {
                message: "unity_catalog_endpoint cannot be empty".to_string(),
            });
        }

        // Validate authentication credentials
        match &self.auth {
            DatabricksAuthentication::OAuth {
                client_id,
                client_secret,
            } => {
                if client_id.inner().is_empty() {
                    return Err(ZerobusSinkError::ConfigError {
                        message: "OAuth client_id cannot be empty".to_string(),
                    });
                }
                if client_secret.inner().is_empty() {
                    return Err(ZerobusSinkError::ConfigError {
                        message: "OAuth client_secret cannot be empty".to_string(),
                    });
                }
            }
            DatabricksAuthentication::LoginService(config) => {
                if config.user.service_principal_resource.is_empty() {
                    return Err(ZerobusSinkError::ConfigError {
                        message: "LoginService service_principal_resource cannot be empty"
                            .to_string(),
                    });
                }
                if config.login_service.login_endpoint.is_empty() {
                    return Err(ZerobusSinkError::ConfigError {
                        message: "LoginService login_endpoint cannot be empty".to_string(),
                    });
                }
            }
        }

        if let Some(max_bytes) = self.batch.max_bytes {
            // Zerobus SDK limits max bytes to 10MB.
            // NOTE: The size of the batch in Vector is not exactly the same as the size of the
            // batch in the SDK since they are encoded differently. Though it is expected that
            // Vector encoded data will be larger than the SDK encoded data since SDK encodes the
            // data in protobuf format.
            if max_bytes > 10_000_000 {
                return Err(ZerobusSinkError::ConfigError {
                    message: "max_bytes must be less than or equal to 10MB".to_string(),
                });
            }
        }

        Ok(())
    }

    /// The user-agent suffix to hand the Zerobus SDK: `Vector/<version>`
    /// alone, or with the user's configured `user_agent` appended. The SDK
    /// prepends its own `zerobus-sdk-rs/<version>` prefix to this value.
    pub fn user_agent_suffix(&self) -> String {
        let vector = format!("Vector/{}", crate::vector_version());
        match self.user_agent.as_deref().filter(|s| !s.is_empty()) {
            Some(ua) => format!("{vector} {ua}"),
            None => vector,
        }
    }
}

// Default value functions
fn default_flush_timeout_ms() -> u64 {
    30000
}

fn default_server_ack_timeout_ms() -> u64 {
    60000
}

fn default_batch_encoding() -> BatchSerializerConfig {
    BatchSerializerConfig::ArrowStream(ArrowStreamSerializerConfig::default())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vector_lib::sensitive_string::SensitiveString;

    fn create_test_config() -> ZerobusSinkConfig {
        ZerobusSinkConfig {
            ingestion_endpoint: "https://test.databricks.com".to_string(),
            table_name: "test.default.logs".to_string(),
            unity_catalog_endpoint: "https://test-workspace.databricks.com".to_string(),
            auth: DatabricksAuthentication::OAuth {
                client_id: SensitiveString::from("test-client-id".to_string()),
                client_secret: SensitiveString::from("test-client-secret".to_string()),
            },
            user_agent: None,
            schema: SchemaSource::UnityCatalog,
            stream_options: ZerobusStreamOptions::default(),
            batch_encoding: default_batch_encoding(),
            batch: Default::default(),
            request: Default::default(),
            acknowledgements: Default::default(),
        }
    }

    #[test]
    fn test_config_validation_success() {
        let config = create_test_config();
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_config_validation_empty_endpoint() {
        let mut config = create_test_config();
        config.ingestion_endpoint = "".to_string();

        let result = config.validate();
        assert!(result.is_err());

        if let Err(crate::sinks::databricks_zerobus::error::ZerobusSinkError::ConfigError {
            message,
        }) = result
        {
            assert!(message.contains("ingestion_endpoint cannot be empty"));
        } else {
            panic!("Expected ConfigError for empty ingestion_endpoint");
        }
    }

    #[test]
    fn test_config_validation_empty_table_name() {
        let mut config = create_test_config();
        config.table_name = "".to_string();

        let result = config.validate();
        assert!(result.is_err());

        if let Err(crate::sinks::databricks_zerobus::error::ZerobusSinkError::ConfigError {
            message,
        }) = result
        {
            assert!(message.contains("table_name cannot be empty"));
        } else {
            panic!("Expected ConfigError for empty table_name");
        }
    }

    #[test]
    fn test_config_validation_invalid_table_name() {
        let mut config = create_test_config();
        config.table_name = "invalid_table".to_string(); // Missing dots

        let result = config.validate();
        assert!(result.is_err());

        if let Err(crate::sinks::databricks_zerobus::error::ZerobusSinkError::ConfigError {
            message,
        }) = result
        {
            assert!(message.contains("catalog.schema.table"));
        } else {
            panic!("Expected ConfigError for invalid table_name format");
        }
    }

    #[test]
    fn test_config_validation_empty_unity_catalog_endpoint() {
        let mut config = create_test_config();
        config.unity_catalog_endpoint = "".to_string();

        let result = config.validate();
        assert!(result.is_err());

        if let Err(crate::sinks::databricks_zerobus::error::ZerobusSinkError::ConfigError {
            message,
        }) = result
        {
            assert!(message.contains("unity_catalog_endpoint cannot be empty"));
        } else {
            panic!("Expected ConfigError for empty unity_catalog_endpoint");
        }
    }

    #[test]
    fn test_config_validation_empty_oauth_credentials() {
        let mut config = create_test_config();
        config.auth = DatabricksAuthentication::OAuth {
            client_id: SensitiveString::from("".to_string()),
            client_secret: SensitiveString::from("test-secret".to_string()),
        };

        let result = config.validate();
        assert!(result.is_err());

        if let Err(crate::sinks::databricks_zerobus::error::ZerobusSinkError::ConfigError {
            message,
        }) = result
        {
            assert!(message.contains("OAuth client_id cannot be empty"));
        } else {
            panic!("Expected ConfigError for empty OAuth client_id");
        }
    }

    /// Exercises the `WireToArrow` branch of `ZerobusSinkConfig::build`
    /// end-to-end, short of the Zerobus stream handshake.
    ///
    /// Under `SchemaSource::UnityCatalog`, `ZerobusService::resolve_arrow_schema`
    /// derives the Arrow output schema directly from the UC table schema via
    /// the SDK helper `arrow_schema_from_uc_schema`. The wire descriptor used
    /// for decoding proto bytes is loaded independently from `desc_file` +
    /// `message_type`. This test proves the two are independent at runtime
    /// by constructing a wire descriptor whose tag numbers (1001/1002/1003)
    /// are deliberately disjoint from anything the UC path could synthesize.
    /// A successful round-trip demonstrates that the UC schema never touches
    /// wire bytes — if it did, wire tags would miss the lookup table and
    /// every column would be null.
    #[cfg(feature = "codecs-arrow")]
    #[test]
    fn wire_to_arrow_uc_source_decouples_arrow_schema_from_wire_descriptor() {
        use super::super::unity_catalog_schema::{UnityCatalogColumn, UnityCatalogTableSchema};
        use arrow::array::AsArray;
        use bytes::Bytes;
        use prost_reflect::prost::Message as _;
        use prost_reflect::prost_types::field_descriptor_proto::{Label, Type as ProtoType};
        use prost_reflect::prost_types::{
            DescriptorProto, FieldDescriptorProto, FileDescriptorProto, FileDescriptorSet,
        };
        use prost_reflect::{DescriptorPool, DynamicMessage, Value as ProtoValue};
        use vector_lib::codecs::encoding::{
            BatchSerializer, BatchSerializerConfig, WireToArrowSerializerConfig,
        };
        use vector_lib::event::{Event, LogEvent};

        // --- UC side: stand in for `ZerobusService::resolve_arrow_schema`
        //     under `SchemaSource::UnityCatalog`. The SDK helper turns a UC
        //     table schema directly into an Arrow schema — no intermediate
        //     proto descriptor — so the UC path has zero opportunity to leak
        //     into wire decode.
        let uc_schema = UnityCatalogTableSchema {
            name: "test_table".into(),
            catalog_name: "test_cat".into(),
            schema_name: "test_sch".into(),
            columns: vec![
                UnityCatalogColumn {
                    name: "name".into(),
                    type_text: "string".into(),
                    type_name: "STRING".into(),
                    position: 0,
                    nullable: true,
                    type_json: String::new(),
                },
                UnityCatalogColumn {
                    name: "id".into(),
                    type_text: "int".into(),
                    type_name: "INT".into(),
                    position: 1,
                    nullable: true,
                    type_json: String::new(),
                },
                UnityCatalogColumn {
                    name: "email".into(),
                    type_text: "string".into(),
                    type_name: "STRING".into(),
                    position: 2,
                    nullable: true,
                    type_json: String::new(),
                },
            ],
        };
        let arrow_schema = databricks_zerobus_ingest_sdk::schema::arrow_schema_from_uc_schema(
            &uc_schema.to_sdk_uc_schema(),
        )
        .unwrap();

        // --- Wire side: a completely separate descriptor, written to a
        //     tempfile so we exercise the `desc_file` → `get_message_descriptor`
        //     path that `BatchSerializerConfig::build` invokes. Field names
        //     intentionally match UC column names so the name-based pairing
        //     at plan build has something to work with; tag numbers are
        //     deliberately disjoint from the UC-synthesized ones.
        let wire_fd = FileDescriptorProto {
            name: Some("wire_to_arrow_uc_split_test.proto".into()),
            package: Some("wire_to_arrow_uc_split_test".into()),
            message_type: vec![DescriptorProto {
                name: Some("Row".into()),
                field: vec![
                    FieldDescriptorProto {
                        name: Some("name".into()),
                        number: Some(1001),
                        label: Some(Label::Optional as i32),
                        r#type: Some(ProtoType::String as i32),
                        ..Default::default()
                    },
                    FieldDescriptorProto {
                        name: Some("id".into()),
                        number: Some(1002),
                        label: Some(Label::Optional as i32),
                        r#type: Some(ProtoType::Int32 as i32),
                        ..Default::default()
                    },
                    FieldDescriptorProto {
                        name: Some("email".into()),
                        number: Some(1003),
                        label: Some(Label::Optional as i32),
                        r#type: Some(ProtoType::String as i32),
                        ..Default::default()
                    },
                ],
                ..Default::default()
            }],
            ..Default::default()
        };
        let set = FileDescriptorSet {
            file: vec![wire_fd],
        };
        let mut set_bytes = Vec::new();
        set.encode(&mut set_bytes).unwrap();
        let desc_file = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(desc_file.path(), &set_bytes).unwrap();

        // --- Replay the WireToArrow branch of `ZerobusSinkConfig::build`
        //     (config.rs:255-269): inject the UC-derived Arrow schema into a
        //     `WireToArrowSerializerConfig`, then run `BatchSerializerConfig::build`.
        let wire_config = WireToArrowSerializerConfig {
            desc_file: desc_file.path().to_path_buf(),
            message_type: "wire_to_arrow_uc_split_test.Row".into(),
            schema: Some(arrow_schema),
        };
        let batch_serializer = BatchSerializerConfig::WireToArrow(wire_config)
            .build()
            .expect("build should succeed with separate UC + wire descriptors");

        // --- Round-trip: encode a Row using the wire descriptor (tags 1001+).
        let wire_desc = DescriptorPool::decode(set_bytes.as_slice())
            .unwrap()
            .get_message_by_name("wire_to_arrow_uc_split_test.Row")
            .unwrap();
        let mut msg = DynamicMessage::new(wire_desc);
        msg.set_field_by_name("name", ProtoValue::String("alice".into()));
        msg.set_field_by_name("id", ProtoValue::I32(42));
        msg.set_field_by_name("email", ProtoValue::String("alice@example.com".into()));
        let mut buf = Vec::new();
        msg.encode(&mut buf).unwrap();
        let mut log = LogEvent::default();
        log.insert("message", Bytes::from(buf));
        let events = [Event::from(log)];

        let batch = match batch_serializer {
            BatchSerializer::WireToArrow(ser) => ser
                .encode_to_record_batch(&events)
                .expect("wire decode with real wire tags"),
            other => panic!("expected WireToArrow serializer, got {other:?}"),
        };

        assert_eq!(batch.num_rows(), 1);
        assert_eq!(batch.num_columns(), 3, "UC-derived arrow schema shape");
        assert_eq!(batch.schema().field(0).name(), "name");
        assert_eq!(batch.schema().field(1).name(), "id");
        assert_eq!(batch.schema().field(2).name(), "email");
        assert_eq!(batch.column(0).as_string::<i64>().value(0), "alice");
        assert_eq!(
            batch
                .column(1)
                .as_primitive::<arrow::datatypes::Int32Type>()
                .value(0),
            42
        );
        assert_eq!(
            batch.column(2).as_string::<i64>().value(0),
            "alice@example.com"
        );
    }

    #[test]
    fn test_user_agent_suffix_without_user_value() {
        let config = create_test_config();
        let suffix = config.user_agent_suffix();
        assert!(
            suffix.starts_with("Vector/"),
            "expected Vector/<version> prefix, got {suffix:?}"
        );
        // No user value configured, so nothing is appended.
        assert!(
            !suffix.contains(' '),
            "unexpected appended value in {suffix:?}"
        );
    }

    #[test]
    fn test_user_agent_suffix_with_user_value() {
        let mut config = create_test_config();
        config.user_agent = Some("my-service/1.2".to_string());
        let suffix = config.user_agent_suffix();
        assert!(
            suffix.starts_with("Vector/"),
            "expected Vector/<version> prefix, got {suffix:?}"
        );
        assert!(
            suffix.ends_with(" my-service/1.2"),
            "expected user value appended, got {suffix:?}"
        );
    }

    #[test]
    fn test_user_agent_suffix_empty_user_value_ignored() {
        let mut config = create_test_config();
        config.user_agent = Some(String::new());
        let suffix = config.user_agent_suffix();
        // An empty string is treated the same as no value: no trailing space.
        assert!(
            !suffix.contains(' '),
            "empty user_agent should be ignored, got {suffix:?}"
        );
    }
}
