[sources.demo]
type = "demo_logs"
format = "json"
interval = 0.01

[sinks.clickhouse]
type = "clickhouse"
inputs = ["demo"]
endpoint = "http://cluster-service-write-headless-testing.logging-clickhouse.svc.cluster.local:8123"
fallback_endpoint = "http://clickhouse-service-logs-write.logging-clickhouse.svc.cluster.local:8123"
table = "vector_logs"
database = "default"
format = "json_each_row"
date_time_best_effort = true
skip_unknown_fields = true
auth.strategy = "basic"
auth.user = "vector-aggregator"
auth.password = "3SC6HCVg"


# Enable headless service mode
use_headless_service = true
# dns_refresh_interval_secs = 30
