apiVersion: v1
kind: Pod
metadata:
  name: vector-debug
  labels:
    app: vector-debug
spec:
  containers:
    - name: vector
      image: harbor-aws-eu-west-1.dev.databricks.com/manual/universe/vector:custom
      imagePullPolicy: Always
      command: ["/usr/local/bin/vector"]
      args: ["--config", "/etc/vector/vector.toml"]
      env:
        - name: VECTOR_LOG
          value: "info"
        - name: RUST_BACKTRACE
          value: "1"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
  restartPolicy: Always
