# Workflow from upstream: Never ran
# Only kept to reduce conflicts while syncing from upstream.

name: Custom Builds

permissions:
  contents: write
  packages: write

jobs:
  Custom:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: custom
    secrets: inherit
