# Workflow from upstream: Never ran
# Only kept to reduce conflicts while syncing from upstream.

name: Deny - Linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/changes.yml
    secrets: inherit

  test-deny:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    if: ${{ always() && (github.event_name != 'pull_request' || needs.changes.outputs.deny == 'true') }}
    needs: [changes]
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.ref }}

      - uses: ./.github/actions/setup
        with:
          mold: false
          cargo-deny: true

      - name: Check cargo deny advisories/licenses
        run: make check-deny
