# Workflow from upstream: Never ran
# Only kept to reduce conflicts while syncing from upstream.

name: Nightly

permissions:
  contents: write
  packages: write

jobs:
  Nightly:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: nightly
    secrets: inherit
